### ISSUE TITLE
Missing dependecy

### ISSUE THREAD

**Issue by bogdancss** [TylerK/react-parallax-hover#2]
Getting `Module not found: Can't resolve 'aphrodite/no-important'`.

**Comment by TylerK** [comment]
@bogdancss I _completely_ forgot about this repo. Apologies for the ... _delayed_ response lol

Version `2.0.0` has just been published and will definitely fix this issue. 

Going to close this as Aphrodite no longer exists in this repo. Feel free to open any new issues.
