### ISSUE TITLE
Rotation not working

### ISSUE THREAD

**Issue by jonathanpz890** [TylerK/react-parallax-hover#24]
The component doesn't rotate at all

![image](https://user-images.githubusercontent.com/54740902/151770184-12cb927f-57b2-46e0-a7f8-4cea7cbe9c43.png)

![rotation](https://user-images.githubusercontent.com/54740902/151769994-5dee827c-14c3-4616-9cf6-dc6baa4dd4a3.gif)

**Comment by TylerK** [comment]
Hey @Jonathanpz890 happy to help, could you share the CSS of those inner divs?

**Comment by TylerK** [comment]
Actually, @Jonathanpz890 if you add an explicit `scale` prop, it will fix the issue. I'll also publish a new version that adds a default for this prop.

Going to close this but feel free to re-open if that doesn't work or anything else comes up :) 

Thanks for bringing this to my attention!
