### ISSUE TITLE
TypeError: Cannot read property 'any' of undefined

### ISSUE THREAD

**Issue by monikatamsoy** [TylerK/react-parallax-hover#3]
React version: 16.13.0
Find the attached image of the 
![Screen Shot 2020-03-15 at 13 45 37](https://user-images.githubusercontent.com/30457975/76697985-97d20200-66c3-11ea-881d-de2b28c4120a.png)
error.

**Comment by monikatamsoy** [comment]
On my forked version, commenting ParallaxHover.propTypes object solves the issue. Any solution to this? I can raise PR on how can we resolve this issue.

**Comment by TylerK** [comment]
@monikatamsoy A quick fix might be to move `react` and `react-dom` out of devDeps (my bad) and move it into deps.

**Comment by TylerK** [comment]
@monikatamsoy I just published version `2.0.0`. Could you upgrade your local version and let me know how it goes? :)

**Comment by monikatamsoy** [comment]
> @monikatamsoy A quick fix might be to move `react` and `react-dom` out of devDeps (my bad) and move it into deps.
